---
title: "A Beginner's Guide to Dashboards: Make Your Visuals Interactive"
author: "Jessie Liang"
date: "2026-01-16"
categories: [news, code, analysis]
---

As information technology is getting more advanced these years, big data is everywhere. Because of that, academic and business organizations are more aware of drawing insights from big bulk of data, hoping to get numerical evidence that aids decision making. However, after collecting massive data, an important question arises: how to get intuitions of this data set without applying complicated analysis? Some may say we can use summary tables that record key calculated statistics. Others would suggest draw a comprehensive fixed graph that is ready to use in reports or slides. Although these options make sense and are widely used, they actually miss one important aspect: interactivity. Why does interaction matter? Well, the explorer of this data set may want to see the data from different angles. By only using tables or fixed charts, a data analyst is needed to constantly update the table or generate a new plot to meet the new ideas of the data explorer, which is very slow, inconvenient, and repetitive.

In this situation where the data explorer wants to peek the data from different perspectives himself/herself, dashboards come as a rescue. With dashboards, the data explorer is no longer a passive viewer of static outputs. Instead, he/she can interact with the raw data by doing simple manipulations such as filtering and selecting. If you are a beginner to dashboard, then this blog is just for you. Here we will briefly discuss the definition, mechanism, motivation and power of dashboards. As a practical guideline, this blog mainly focuses on two aspects in detail: interactive elements and visual types, including what they are and how to use them.

## Introduction to Dashboards

A dashboard is an interactive visual tool that allows users to discover patterns from the raw data in a self-driven way. Unlike static ones, dashboards can receive, process, and respond to user inputs. Whenever a response is received from an interactive element, such as answering a multiple choice question, the visuals will be updated automatically to align with the user inputs, without manual efforts. Sounds cool? Yes it is!

Roughly speaking, there are two basic yet important parts of dashboards:

1.  Interactive elements: These are user-facing "interface" that allow users to input their choices, thus controlling what data is used to generate results behind the scenes.

2.  Visual types: These are the final products delivered to users, which typically include plots and/or tables which are dynamic and responsive to user inputs.

These two parts work in tandem, with one collecting users' intentions and the other showing results accordingly. As a concrete example, a dashboard has a slider that asks you to select the start and end year of the analysis period. With these years given, the dashboard then automatically generates a line chart showing the trend of sales between the given start and end year. This is the strength of using a dashboard: now we do not need to email a data analyst back and forth to ask for many different line charts with different start and end years. Rather, we can do all of this ourselves!

## Commonly used Interactive Elements

The unique component that distinguishes dashboards from static visuals is the interactive element. In fact, interactive elements enable users to control the dashboard. Based on user inputs, the dashboard then decides the underlying data to display, such as what subset of data should be included in plotting.

Here in this blog, I will introduce 4 frequently used interactive elements, which are also my favorites:

### 1. Drop-down Menu

A drop-down menu is a collection of all possible choices at which users can click to select. Depending on the setting of the dashboard, users may be allowed to select only one value, or sometimes multiple selections are permitted.

**Use cases of drop-down menu**:

-   Choose a continent

-   Select departments of a company

-   Pick a year to analyze the sales data

**Dos and Don'ts**:

-   Don't use a drop-down menu when there are too many choices to select from

-   Do use a drop-down menu when the options are discrete (and Don't use it when the options are continuous)

Drop-down menus are simple and intuitive to use. Since they seem familiar to many users, they are one of the most common choices used in dashboards.

### 2. Slider

A slider is a bar of values with a constant step size that shows a predefined range of numbers. Depending on the setting of the dashboard, users may pick a single value or a range of values from the slider by dragging the handle along the bar.

**Use cases of sliders**:

-   Select the range of the sales period

-   Pick a price interval and analyze the categories of goods with these prices

**Dos and Don'ts**:

-   Do set a reasonable step size, so that the consecutive values are not too close or too far away when compared to the length of the bar,

-   Don't use slider for the data that cannot be ordered, since we should be able to compare and order different values.

Sliders are handy for understanding patterns over time or across a range of values of some data. They are also easy to use and implement.

### 3. Hover Data

Hover data shows additional details of the hovered point or region in a plot. What extra information is included in the pop-up text box can be controlled by the dashboard design.

**Use cases of hover data**:

-   Show the world rank of the country's consumption when hovering mouse over this country on the map

-   Show the exact numeric value of a line chart when hovering mouse over a point on the line

**Dos and Don'ts**:

-   Do use hover data to avoid overcrowding information in the plot

-   Do use hover data to show additional useful details that cannot be listed out explicitly

### 4. Cross-Filtering

Cross-filtering links different plots together. With cross-filtering, other plots will be adjusted automatically based on the user interactions with one particular plot.

**Use cases of cross-filtering**:

-   Clicking Canada on the map updates another line chart to show only Canadian data.

-   Hovering mouse in a line chart on a particular year updates another bar chart to include only the data of that selected year.

Cross-filtering is an advanced and powerful technique. Because of it, dashboards become coordinated entities instead of unrelated and independent pieces.

## Visual Types

Though dashboards have additional functions than static visuals, they are actually built upon static plots. After integrating interactive elements, dashboards still need static plots as carriers to convey graphical information. In this blog, I will talk about 4 basic yet useful types of plots:

### 1. Maps

Maps show the variation and/or distribution of data across different geographic locations. They are often used when regional patterns matter and location is a major variable to consider.

**Use cases of maps**:

-   Population of countries colored by value

-   Total sales by province with numbers as labels on top of each province

As mentioned above, labels and/or color intensity are usually adopted to represent numeric values.

### 2. Line Charts

Line charts are the most ideal candidate to plot the trend of a numeric variable over time.

**Use cases of line charts**:

-   How did the CPI index change over the past 10 years?

-   Did monthly sales generally increase or decrease in the past year?

Line charts can have only one line in the plot or several lines colored by another categorical variable which facilitates comparison.

### 3. Bar Charts

Bar charts are suitable to compare numerical values across different levels of a categorical variable. Since human eyes are good at comparing length of bars with the same starting position, bar charts are perfect for comparing the magnitude of numerical values.

**Use cases of bar charts**:

-   Top 5 countries with largest population in Asia

-   Number of students by department

But note that bar charts are only informative given the number of categories is restricted. With too many categories, the plot becomes messy.

### 4. Stacked Area Chart

Stacked area charts demonstrate what percentage each category accounts for when compared to the total. In particular, they are useful when you are interested in how each component contributes to the total. Another caveat is that stacked area chart is only intuitive when the number of categories is small enough.

Nevertheless, there are also obvious drawbacks for this type of plot: It is hard to compare the exact value of individual portions, since their starting positions are different. In other words, if precise comparison is the goal, then stacked area chart should not be used and you might proceed with bar charts.

Therefore, this type of visualization is sometimes controversial and should be used with care.
